FROM impfs_base_docker_image

RUN echo edit to rebuild...

RUN eval `opam config env` && opam pin add -n tjr_lib_core https://github.com/tomjridge/tjr_lib.git && opam pin add -n tjr_lib https://github.com/tomjridge/tjr_lib.git && opam install tjr_lib
